// This file is regenerated by `wails dev` / `wails build` from app/app.go.
// The hand-edited stubs below let `vite build` succeed without first running wails.

import type { analyse } from '../models';

export function OpenFileDialog(): Promise<string>;
export function DistinctAuthors(path: string): Promise<string[]>;
export function Analyse(path: string, me: string, them: string, gapHours: number): Promise<analyse.Stats>;
