// This file is regenerated by `wails dev` / `wails build`.
export function OpenFileDialog() { return window['go']['main']['App']['OpenFileDialog'](); }
export function DistinctAuthors(path) { return window['go']['main']['App']['DistinctAuthors'](path); }
export function Analyse(path, me, them, gapHours) { return window['go']['main']['App']['Analyse'](path, me, them, gapHours); }
