// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Analyse(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.StatsDTO>;

export function DistinctAuthors(arg1:string):Promise<Array<string>>;

export function OpenFileDialog():Promise<string>;
