// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyse(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Analyse'](arg1, arg2, arg3, arg4);
}

export function DistinctAuthors(arg1) {
  return window['go']['main']['App']['DistinctAuthors'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveJpeg(arg1, arg2) {
  return window['go']['main']['App']['SaveJpeg'](arg1, arg2);
}
